version: "3.1"
services:
  mongo:
    image: mongo
    restart: always
    ports:
      - 27017:27017
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: root
    volumes:
      - D:/database/volumes/mongo/mount:/data/db

  redis-compose:
    image: redis
    command: redis-server --requirepass root
    hostname: redis
    ports:
      - "6379:6379"
    volumes:
      - D:/database/volumes/redis/mount:/data

  postgres:
    image: postgres
    restart: always
    volumes:
      - D:/database/volumes/postgres/mount:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: root
      POSTGRES_PASSWORD: root
    ports:
      - "5432:5432"

  zookeeper:
    image: 'bitnami/zookeeper:latest'
    volumes:
      - D:/database/volumes/zookeeper:/bitnami/zookeeper
    environment:
      ALLOW_ANONYMOUS_LOGIN: 'yes'

  kafka:
    image: 'bitnami/kafka:latest'
    volumes:
      - D:/database/volumes/kafka:/bitnami/kafka
    ports:
      - "9092:9092"
    environment:
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka:9092
      ALLOW_PLAINTEXT_LISTENER: 'yes'
    depends_on:
      - zookeeper

  kafdrop:
    image: obsidiandynamics/kafdrop
    ports:
      - "9000:9000"
    environment:
      KAFKA_BROKERCONNECT: kafka:9092
      JVM_OPTS: "-Xms32M -Xmx64M"
    depends_on:
      - kafka

  rabbitmq:
    image: rabbitmq:management
    hostname: rabbitmq
    volumes:
      - D:/database/volumes/rabbitmq:/var/lib/rabbitmq
    ports:
      - "5672:5672"
      - "15672:15672"

networks:
  net:
    driver: bridge
