
spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/postgres?currentSchema=schema_order
    username: root
    password: root

  jpa:
    hibernate:
      ddl-auto: update
      dialect: org.hibernate.dialect.PostgreSQLDialect
    properties:
      hibernate:
        show_sql: true
    open-in-view: false

  data:
    redis:
      host: localhost
      password: root
      port: 6379
      database: 1

feign:
  client:
    zipCode:
      url: ${ZIP_CODE_URL:http://localhost:3001/cep}